language: node_js

node_js:
  - "7"

sudo: required
addons:
  chrome: stable

env:
  global:
    - CODECOV_TOKEN="38702dcb-0848-4a8a-a1d3-f97f0197a193"
  
before_install: 
  - npm i -g npm@5.8.0
  - npm install codecov -g

script:
  - npm run test
  - npm run build:aot
  - npm run build:lib
  # start server in the background
  - npm run start -- --silent &
  # run all Cypress tests and record on the dashboard
  - npm run cy:run:record -- --record
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  # this avoids flake in Travis jobs
  - kill $(jobs -p) || true

after_success:
  - npm run codecov